repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix", "lx_dtypes", "tests"]
        pass_filenames: false
      - id: ruff-format
        args: ["lx_dtypes", "tests"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: mypy
        name: mypy type check
        entry: mypy lx_dtypes
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest suite
        entry: pytest
        language: system
        pass_filenames: false
