[project]
authors = [
  {name = "Thomas J. Lux", email = "lux_t1@ukw.de"},
]
description = "lx-data-types"
maintainers = [
  {name = "Thomas J. Lux", email = "lux_t1@ukw.de"},
]
name = "lx-dtypes"
readme = "README.md"
version = "0.0.0.1"

classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: Medical Science Apps.",
  "Programming Language :: Python :: 3.12",
]

dependencies = [
  "icecream>=2.1.4",
  "numpy>=2.2.3",
  "opencv-python>=4.11.0.86",
  "pandas>=2.2.3",
  "pillow>=11.3.0",
  "pydantic>=2.10.6",
  "pytest>=8.3.5",
  "python-ffmpeg>=2.0.12",
  "pyyaml>=6.0.2",
  "scikit-learn>=1.5.2",
  "scipy>=1.16.1",
  "openpyxl>=3.1.5",
  "mypy>=1.16.0",
  "requests>=2.32.3",
]
requires-python = ">=3.12,<3.13"

[project.optional-dependencies]
dev = [
  "pytest-cov>=6.1.1",
  "pytest-env>=1.1.5",
  "pytest-mypy-plugins>=3.2.0",
  "pytest-django>=4.11.1",
  "pytest-xdist>=3.8.0",
  "pip>=25.2",
  "ruff>=0.14.0",
  "build>=1.3.0",
  "flake8>=7.3.0",
  "twine>=6.2.0",
]


[project.urls]
Homepage = "https://info.coloreg.de"
Repository = "https://github.com/wg-lux/lx-data-models"





[tool.mypy]
plugins = [""]
strict = true
exclude = '^(.venv|venv|env)/'

# [tool.pytest.ini_options]

[tool.hatch.build]
exclude = [
  "tests",
  "tests/**",
]

[tool.setuptools]
packages = ["lx_dtypes"]

[tool.hatch.build.targets.wheel]
packages = ["lx_dtypes"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.sdist]
exclude = [
  "tests",
  "tests/**",
  "docs/production",
  "docs/production/**",
  "htmlcov",
  "htmlcov/**",
  "storage",
  "storage/**",
]
